Add heat template for validate openstack, remove tripleo-ci deps
* Add the heat template for the ping test
* Remove the dependencies of the tripleo-ci repo

Change-Id: I8b3bf41353a2fdc97bd718552b0aa3ebaa3e4416

diff --git a/templates/overcloud-validate.sh.j2 b/templates/overcloud-validate.sh.j2
--- a/templates/overcloud-validate.sh.j2
+++ b/templates/overcloud-validate.sh.j2
@@ -1,8 +1,36 @@
 #!/bin/bash
 # Validate the overcloud deployment
-
 set -eux
-
+source {{ working_dir }}/overcloudrc
 {% if test_ping|bool %}
-{% include 'tripleo-pingtest.sh.j2' %}
+# create test ping stack
+heat stack-create {{ validate_stack_name }} --template-file  {{ validate_template }}
+# wait for stack complete or failed
+/bin/bash /usr/libexec/openstack-tripleo/wait_for -w 300 --delay 10 \
+--success-match {{ validate_success_status }} -- heat stack-show {{ validate_stack_name }}
+
+if [[ $? == 0 ]]; then
+    # get the floating ip
+    novaid=`nova list|grep {{ validate_server_name }} |awk  '{print $2}'`
+    floating_ip=`nova floating-ip-list | grep $novaid | awk  '{print $4}'`
+    ping -c 1 $floating_ip
+else
+    ping -c 1 $floating_ip || :
+    nova show Server1 || :
+    nova service-list || :
+    neutron agent-list || :
+    nova console-log Server1 || :
+    echo "Overcloud validate Failed"
+    exit 1
+fi
+if [[ $? == 0 ]]; then
+    # clean env
+    /usr/bin/yes | heat stack-delete {{ validate_stack_name }}
+    if tripleo wait_for -w 300 -d 10 -s "Stack not found" -- "openstack stack show tenant-stack"; then
+        echo "Heat stack delete"
+    else
+        echo "Failed to delete stack, please check manually"
+    fi
+fi
+exit $?
 {% endif %}
